name: Prüfung

on: 
  push:
    branches:
      - main

jobs:
    lint:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install Dependencies
              run: npm install

            - name: Run Linter
              run: npm run lint
    
    test:
        name: Run Tests
        runs-on: ubuntu-22.04
        needs: lint
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install Dependencies
              run: npm install

            - name: Run Tests
              run: npm test

